# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 567ec263b1e2ceb0ab4316f76e056bcb2b3b5a12feaef999d27b7e42f138fe31564bca9c65624858492029e07d9c56084a8a29fe201b872d5145a13e7935c2a5

test:
  secret_key_base: 1f19657d6be7749a1676bf9f61e646164a2dfe1985ccee2df2792e41c320828f44a99296363b49d79acb9f23dc4717d360e9bb9750506d9cf27b7729b192850b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
